version = [4, 0]  # IPC4 simple format (no Intel CSS/CSE)

[adsp]
name = "imx8m-ipc4"
image_size = "0x800000"  # 8MB total image size
alias_mask = "0x0"

[[adsp.mem_alias]]
type = "cached"
base = "0x0"

[[adsp.mem_alias]]
type = "uncached"
base = "0x0"

[[adsp.mem_zone]]
type = "IRAM"
base = "0x3B6F8000"
size = "0x800"
host_offset = "0x10000"

[[adsp.mem_zone]]
type = "DRAM"
base = "0x3B6E8000"
size = "0x8000"
host_offset = "0x0"

[[adsp.mem_zone]]
type = "SRAM"
base = "0x92400000"
size = "0x800000"
host_offset = "0x0"
